language: ruby
env:
  - CPLUS_INCLUDE_PATH=/usr/include/atlas C_INCLUDE_PATH=/usr/include/atlas
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

script: bundle install && bundle exec rake spec

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
  - sudo apt-get install -qq libatlas-base-dev
